# Generated by Django 6.0 on 2025-12-30 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='uniq_tournament_name_country')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='matches.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minutes_watched', models.CharField(choices=[('LT_30', "Less than 30'"), ('ONE_HALF', 'One half'), ('ALMOST_ALL', 'Almost all'), ('FULL', 'Full match')], max_length=20)),
                ('review', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'created_at'], name='matches_rat_match_i_54dd9a_idx'), models.Index(fields=['user', 'created_at'], name='matches_rat_user_id_1923f1_idx'), models.Index(fields=['score'], name='matches_rat_score_f4aedb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'match'), name='uniq_user_match_rating'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='rating_score_0_100')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date_time'], name='matches_mat_date_ti_31b488_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'date_time'], name='matches_mat_tournam_084223_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team', 'date_time'], name='matches_mat_home_te_c6d74b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team', 'date_time'], name='matches_mat_away_te_01126b_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_home_team_not_away_team'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'date_time', 'home_team', 'away_team'), name='uniq_match_identity'),
        ),
    ]
