# Generated by Django 6.0 on 2026-01-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name="tournament",
            name="external_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="external_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="match",
            name="external_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="venue",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["external_id"], name="matches_tou_external_5fbb7c_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["external_id"], name="matches_tea_external_c2cfd3_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["external_id"], name="matches_mat_external_4f1b4b_idx"),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                condition=models.Q(external_id__isnull=False),
                fields=("external_id",),
                name="uniq_tournament_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(external_id__isnull=False),
                fields=("external_id",),
                name="uniq_team_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(external_id__isnull=False),
                fields=("external_id",),
                name="uniq_match_external_id",
            ),
        ),
    ]
