# Generated by Django 6.0 on 2026-01-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_external_ids_and_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="code",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="tournament",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["code"], name="matches_tou_code_0ad2db_idx"),
        ),
    ]
