# Generated by Django 6.0 on 2026-01-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tournament_code_logo_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_externa_3e0c20_idx',
            old_name='matches_mat_external_4f1b4b_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='matches_tea_externa_ee9788_idx',
            old_name='matches_tea_external_c2cfd3_idx',
        ),
        migrations.RenameIndex(
            model_name='tournament',
            new_name='matches_tou_externa_c44b9c_idx',
            old_name='matches_tou_external_5fbb7c_idx',
        ),
        migrations.RenameIndex(
            model_name='tournament',
            new_name='matches_tou_code_1756dc_idx',
            old_name='matches_tou_code_0ad2db_idx',
        ),
    ]
