# Generated by Django 6.0 on 2026-01-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_rename_matches_mat_external_4f1b4b_idx_matches_mat_externa_3e0c20_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rating",
            name="stadium_photo_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rating",
            name="representative_photo_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rating",
            name="featured_note",
            field=models.CharField(blank=True, default="", max_length=240),
        ),
        migrations.AddField(
            model_name="rating",
            name="featured_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="featured_primary_image",
            field=models.CharField(
                choices=[
                    ("representative", "Representative"),
                    ("stadium", "Stadium"),
                ],
                default="representative",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                condition=models.Q(("featured_order__isnull", False)),
                fields=("user", "featured_order"),
                name="uniq_user_featured_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                condition=models.Q(("featured_order__isnull", True))
                | (models.Q(("featured_order__gte", 1)) & models.Q(("featured_order__lte", 4))),
                name="rating_featured_order_1_4",
            ),
        ),
    ]
