"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-s1j1dz9++1_(c9+j*r=pr*9@=vmov(j_x-1!9(@gs58h^eg7^$",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
    'matches',
    'social',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000",
    ).split(",")
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

FOOTBALL_DATA_TOKEN = os.getenv("FOOTBALL_DATA_TOKEN", "")
FOOTBALL_DATA_BASE_URL = os.getenv(
    "FOOTBALL_DATA_BASE_URL",
    "https://api.football-data.org/v4",
)
FOOTBALL_DATA_TIMEOUT_SECONDS = float(
    os.getenv("FOOTBALL_DATA_TIMEOUT_SECONDS", "20")
)
FOOTBALL_DATA_CONNECT_TIMEOUT_SECONDS = float(
    os.getenv("FOOTBALL_DATA_CONNECT_TIMEOUT_SECONDS", "5")
)
FOOTBALL_DATA_READ_TIMEOUT_SECONDS = float(
    os.getenv("FOOTBALL_DATA_READ_TIMEOUT_SECONDS", "20")
)
FOOTBALL_DATA_WRITE_TIMEOUT_SECONDS = float(
    os.getenv("FOOTBALL_DATA_WRITE_TIMEOUT_SECONDS", "20")
)
FOOTBALL_DATA_POOL_TIMEOUT_SECONDS = float(
    os.getenv("FOOTBALL_DATA_POOL_TIMEOUT_SECONDS", "20")
)
FOOTBALL_DATA_RATE_LIMIT_PER_MINUTE = int(
    os.getenv("FOOTBALL_DATA_RATE_LIMIT_PER_MINUTE", "10")
)
FOOTBALL_DATA_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("FOOTBALL_DATA_RATE_LIMIT_WINDOW_SECONDS", "60")
)
FOOTBALL_DATA_HTTP_MAX_ATTEMPTS = int(
    os.getenv("FOOTBALL_DATA_HTTP_MAX_ATTEMPTS", "3")
)
FOOTBALL_DATA_RETRY_AFTER_FALLBACK_SECONDS = int(
    os.getenv("FOOTBALL_DATA_RETRY_AFTER_FALLBACK_SECONDS", "60")
)
FOOTBALL_DATA_THROTTLE_SECONDS = float(
    os.getenv("FOOTBALL_DATA_THROTTLE_SECONDS", "1")
)
FOOTBALL_DATA_CACHE_SECONDS = int(os.getenv("FOOTBALL_DATA_CACHE_SECONDS", "600"))
FOOTBALL_DATA_MATCHES_MAX_RANGE_DAYS = int(
    os.getenv("FOOTBALL_DATA_MATCHES_MAX_RANGE_DAYS", "10")
)
IMPORT_MATCHES_RANGE_DAYS = int(os.getenv("IMPORT_MATCHES_RANGE_DAYS", "0"))
IMPORT_MATCHES_FREQUENCY_MINUTES = int(
    os.getenv("IMPORT_MATCHES_FREQUENCY_MINUTES", "10")
)
IMPORT_MATCHES_WEEKDAY_MINUTES = int(
    os.getenv("IMPORT_MATCHES_WEEKDAY_MINUTES", "10")
)
IMPORT_MATCHES_WEEKEND_MINUTES = int(
    os.getenv("IMPORT_MATCHES_WEEKEND_MINUTES", "10")
)
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

# Shared secret for protected internal cron endpoints (/internal/*).
CRON_SECRET = os.getenv("CRON_SECRET", "") or os.getenv("CRON-SECRET", "")
